public/_locales/cs/messages.json
- Added translations to the values in the `messages.json` file from English to Czech
Add translation: Czech #14
=> finished messages.json translation

public/_locales/fr/messages.json
=> Add french translation

public/_locales/th/messages.json
=> Add Thai language

public/_locales/ru/messages.json
Russian localization was added in scope of this PR
#7
=> Add russian translation

public/_locales/es/messages.json
Spanish localization added
[#2](https://github.com/devmount/third-stats/issues/2)
=> Add spanish translation

public/_locales/pt/messages.json
=> Fix issue #6: Add Portuguese translation 

public/_locales/it/messages.json
Added italian translation of the project to fix #1
=> Fix Issue #1: added italian translation

public/_locales/ca/messages.json
=> Add Catalan translation

public/_locales/gl/messages.json
**Provide the name and the two-letter code of the new language**
Galician, `gl`
Steps to add the translation
- Add a folder named like the two-letter code of the language you want to add under `public/_locales/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request
=> Add Galician translation

public/_locales/pl/messages.json
* Filling out the template is required.
* All new code must have been tested to ensure against regressions
No changes, just added new language
Added Polish translation
#21 
Please check out why its so tricky with plurals: https://poedit.net/trac/wiki/Doc/PluralForms
=> PL translation

public/_locales/de/messages.json, public/_locales/en/messages.json, src/Stats.vue
Adds a loading indicator for the chart area instead of showing empty charts while processing email data.
Better UX while waiting
Closes #39
=> ➕ loading indicator

src/Stats.vue, src/charts/HeatMap.vue
Labels containing weekdays were wrong. Also the label handling of Heatmaps was improved.
More accurate labeling. More general use of Heatmaps.
none
=> 🔨 fix date labels

public/_locales/de/messages.json, public/_locales/en/messages.json, src/Stats.vue, src/charts/BarChart.vue, src/charts/LineChart.vue, src/utils.js
Adding horizontal bar charts to display email addresses most received emails from or most sent emails to.
Additional analysis to complete this add-on.
Closes #17
=> ➕ most contacted

src/Stats.vue
Featured numbers are now centered on all viewport widths.
Layout looks more focused, especially on ultra-wide screens
Closes #46
=> 🔨 center featured numbers

public/_locales/ca/messages.json, public/_locales/cs/messages.json, public/_locales/de/messages.json, public/_locales/en/messages.json, public/_locales/es/messages.json, public/_locales/fr/messages.json, public/_locales/gl/messages.json, public/_locales/hi/messages.json, public/_locales/it/messages.json, public/_locales/pl/messages.json, public/_locales/pt/messages.json, public/_locales/ru/messages.json, public/_locales/th/messages.json, src/Stats.vue, src/popup.js, src/stats.js
Reorganized language labels and completed lang keys for all languages (still need to be translated though).
More concise language keys.
none
=> 💚 improve language labels

public/_locales/fr/messages.json
Greetings from France  🥖 🍷
Relative to #52
=> Improve French translation 🥖

public/_locales/it/messages.json
- Added missing translations in the `messages.json` file from English to Italian
Complete translation: Italian #55
=> Complete translation: Italian

public/_locales/cs/messages.json
Complete Czech translation #50
=> add Czech translations

public/_locales/es/messages.json
Translate keys to Spanish
Related to [Issue](https://github.com/devmount/third-stats/issues/51)
=> :green_heart: Translated to ES

public/_locales/hi/messages.json
Translated public/loacl/hi/message.json line - 24-25, 56-57, 60-61 to hindi
=> translated to hindi

public/_locales/pl/messages.json
Added polish translation to those lines 24-25, 56-57, 60-61
=> :green_heart: Translated to PL

public/_locales/pt/messages.json
I just finished the translation for portuguese in these lines that was missing
=> finish translate to portuguese

src/Stats.vue, src/charts/HeatMap.vue
Reimplementation of the Heatmap component to use CSS grid instead of flexbox
No misalignment of cols or rows anymore, better label positioning
Closes #74
=> 🔨 fix heatmap implementation

public/_locales/ja/messages.json
=> Add Japanese localization

src/Stats.vue, src/charts/HeatMap.vue
Adjust the CSS grid to make the cells most likely square (depending on the given column space). Additional properties to adjust grid gap and border radius.
Improved visualization of data with heatmaps
Closes #78
=> 💚 heatmap improvements

public/api/LegacyPrefs/implementation.js, public/api/LegacyPrefs/schema.json, public/manifest.json, src/Stats.vue
Add LegacyPrefs API and implement user defined start of week
The already existing Thunderbird setting is used to generate charts according to the configured start of week
Closes #72
=> ➕ user defined start of week

public/_locales/th/messages.json
Translation of the public/_locales/th/messages.json 
Complete Thai translation
#59
=> Update Thai translation

public/_locales/sv/messages.json
Translated into Swedish. Made this new pull request because last one failed.
The more translations the better.
#80
=> Swedish (sv) translation done

public/_locales/ca/messages.json
Added some translations in ca/messages.json
Now the translations are well
=> Add catalan translations

src/Popup.vue, src/Stats.vue, src/assets/global.styl, src/charts/HeatMap.vue
handle global styles on one play, organize colors in corresponding variables
Styles are more flexible and adaptable
None
=> 💚 reorganize styles

public/popup.html, src/Popup.vue, src/Stats.vue, src/assets/global.styl
Additional light theme and mode switch for stats page
Users prefering light color scheme are not limited to a dark theme.
Closes #85
=> 💚 light theme

public/_locales/tr/messages.json
Turkish translations added
Added Turkish Translation.
=> Add Turkish translations

public/_locales/en/messages.json, src/Stats.vue, src/assets/global.styl, src/charts/HeatMap.vue, src/utils.js
This PR completely revamps the top area. It merges the existing years/months chart into a tab area adding quarters and weeks charts. It adds an activity heatmap showing mail counts of every day per year. Also the line chart area can be expanded for a higher resolution of the x-axis.
More charts and additional metric in the same space.
Closes #12 and #99
=> 💚 revamp top chart area

public/_locales/de/messages.json
Adds missing German translation values
Closes #104
=> 🔨 complete German translation

public/_locales/zh-cn/messages.json
Fix: Missing Simplified Chinese Translation
complete missing simplified Chinese translation
Closes #116
=> Fix: Missing Simplified Chinese Translation

public/_locales/zh-tw/messages.json
💫 update translations of Traditional Chinese.
https://github.com/devmount/third-stats/issues/117
=> 💫 update translations of Traditional Chinese.

public/_locales/tr/messages.json
- Turkish translation update
https://github.com/devmount/third-stats/issues/115
=> Turkish Translation update

public/_locales/fr/messages.json
=> feat: improve french translation 🥖

public/_locales/gl/messages.json
=> Update Galician translation

public/_locales/ca/messages.json
=> Complete Catalan translation

public/_locales/cs/messages.json
=> complete cs translation

public/_locales/it/messages.json
Changed Italian message json. Rows 93-94 are left unchanged because it is more understandable that way.
Completed italian transaltaion
#108
=> Complete translation: Italian #108

public/_locales/sv/messages.json
Translated into Swedish.
Updated translation.
#113
=> Translated into swedish (issue #113)

public/_locales/ja/messages.json
=> Update Japanese l10n

public/stats.html, src/Stats.vue
Title of Thunderbird tab will be dynamically updated with the current selected account. Favicon is added.
Better UX.
Closes #132
=> 💚 improve messenger tab

public/_locales/en/messages.json, public/js/background.js, public/manifest.json, src/Options.vue, src/Popup.vue, src/Stats.vue, src/assets/global.styl
Additional Option to enable or disable accounts.
More control about which accounts will be evaluated and which won't.
Closes #151
=> Manage accounts option

src/Stats.vue, src/assets/global.styl
This adds hover styles for form elements.
Better UX
None
=> Improve form styles

src/Options.vue, src/Stats.vue, src/assets/global.styl, src/charts/HeatMap.vue
This implements space for filter form elements.
- extendable
- responsive
Looks like this on different viewport widths:
Closes #162
=> Filter area

public/_locales/en/messages.json, src/Stats.vue
Make examples in tooltips dynamic to show current date. Support <kbd>Enter</kbd> key to apply period filter.
Improved UX.
None
=> Filter period improvements

public/_locales/en/messages.json
Changes the label of the date range filter.
Implements suggested improvements in issue mentioned below.
#188
=> Change Time Period -> Date range

public/_locales/en/messages.json, src/Stats.vue, src/assets/global.styl
Adds information about how old the displayed data is in an information section below the filter.
Live update passed time in human readable units. Shows the specific data retrieval date in a tooltip on hover.
#176
=> Meta timestamp

src/Stats.vue, src/assets/global.styl
Adds a top page progress indication bar, when data is retrieved.
A possibility for the user to see the actual progress.
Closes #201
=> ➕ progress indicator

public/_locales/en/messages.json, public/options.html, src/Options.vue, src/Popup.vue, src/Stats.vue, src/assets/global.styl
Options can now be opened fullpage in an own tab. Corresponding gear icon links are in the popup menu as well as on the stats page.
Options can be accessed more easily.
#195
=> Own Option Page

src/Stats.vue
Despite the default receivers, CC and BCC are now also taken into account for self message recognition.
More accurate pure self message numbers.
Fixes #214
=> 🔨 include cc and bcc in self message recognition

src/Popup.vue
Adding multi-color hover effect on popup icons.
=> 💚 improve hover effect of stats and options icon

public/_locales/en/messages.json, src/Options.vue
Adds possibility to reset options to their default values. Also improves code to handle default option values.
Additional action button to reset options.
Closes #237
=> Reset options

public/_locales/en/messages.json, src/Stats.vue, src/charts/DoughnutChart.vue, yarn.lock
Introduces a new chart type "doughnut" for showing the distribution of emails in folders. Folder sizes are visible in arc size and color intensity.
Added metric about messages counts per folder.
#228
=> Folder stats

README.md, SECURITY.md
Move security hints to security policy, updates security policy, adds a tldr to readme for summarizing security policy (which the majority of users doesn't read,  unfortunately)
documentation ftw
none
=> Update security policy

README.md, public/_locales/ca/messages.json, public/_locales/cs/messages.json, public/_locales/de/messages.json, public/_locales/en/messages.json, public/_locales/es/messages.json, public/_locales/fr/messages.json, public/_locales/gl/messages.json, public/_locales/hi/messages.json, public/_locales/hu/messages.json, public/_locales/it/messages.json, public/_locales/pl/messages.json, public/_locales/pt/messages.json, public/_locales/ru/messages.json, public/_locales/sv/messages.json, public/_locales/th/messages.json, public/_locales/tr/messages.json
Suggestion:
Change `Self Message` to `Message to Self`
Change `Self Messages` to `Messages to Self`
Self message could mean automated messages.
If you want this change please advise and we can send a pull request for L58 and L61.
Thank you
=> hu translation and 1-character ellipses

src/Stats.vue, src/options.js, src/popup.js, src/stats.js
Implement Hungarian Translation
Additional language thanks to @ovari 👏🏻
none
=> Implement Hungarian

public/_locales/en/messages.json, src/Stats.vue
Additional stats filter for contacts, which shows stats for all messages, where this contact is the sender or one of the recipients. This filter provides a drop-down list of all email addresses shown in the most contacted charts.
Possibility to gain detailed insights about a specific contact.
#193
=> Contact filter

src/Options.vue, src/Popup.vue, src/Stats.vue, src/charts/BarChart.vue, src/charts/DoughnutChart.vue, src/charts/HeatMap.vue, src/charts/LineChart.vue, src/definitions.js, src/options.js, src/parts/LiveAge.vue, src/popup.js, src/stats.js, src/utils.js, vue.config.js
No change of UI or functionality, just refactoring the codebase. The following in particular:
- Use double quotes as top level and single quotes as secondary level quotation
- use `const` instead of `let` wherever possible
- use `forEach` instead of `map` if mapped array isn't modified (anti pattern)
Cleaner and more consistent codebase
None
=> Refactor codebase

README.md
Fixes badge links and removes markdown linter warnings.
Correct link targets.
None
=> 📜 fix badge links and formatting

public/_locales/en/messages.json, src/Stats.vue, src/assets/global.styl, src/definitions.js, src/utils.js
Adds an additional featured number: Number of emails flagged as junk. With an average junk score of all emails.
Also another contacts bar chart showing the contacts whose emails have been flagged as junk.
Information about junk emails. Possibility to see, which authors sent the highest number of emails flagged as junk.
#128
=> Junk metrics

src/Options.vue, src/Popup.vue, src/Stats.vue, src/utils.js
New default values:
- dark mode: off
- vertical axis: shown
- start of week: based on TB locale
- accounts: all activated
Less author opinionated default values.
Closes #272
=> Revamp default options

yarn.lock
Fix known security issues in ssri dependency
Prevent denial of service attacks.
None
=> 🔁 upgrade dependencies

.github/workflows/codeql-analysis.yml
Updates CodeQL action definition.
Fixes deprecated setting.
None
=> 🔨 fix deprecated PR setting

src/Stats.vue, src/charts/BarChart.vue, src/charts/LineChart.vue
This change introduces dashed line style for the last segment of line charts.
Indication that the last data point isn't final yet.
#310
=> Data in progress indication

package.json, src/charts/DoughnutChart.vue, yarn.lock
Configure tooltips of doughnut charts to appear directly on the section, the mouse is over.
Expected position of tooltip restored.
Closes #313
=> Fix doughnut tooltips

public/manifest.json, public/options.html, public/popup.html, public/stats.html, src/Popup.vue, src/assets/global.styl, src/chart.config.js, src/charts/LineChart.vue
This change improves markup, adds support for gradients with hex alpha value, implements adaptability of popup appearance to the selected theme (dark or light), improves readibility by increasing font-weight, improves accessibility by increases icon stroke width and fixes a type error for dashed borders in line charts.
Support for both: Thunderbird 78 and 91
#320
=> Support Thunderbird 91

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/new_translation.md
Updating docs and GitHub template files.
Thunderbird version and translation management are now up-to-date.
none.
=> Update GitHub content

package.json, public/_locales/zh-Hant-TW/messages.json
Two commands to handle localization with localazy were added:
```bash
yarn pull-translations # downloads all translations
yarn push-translations # uploads new and overwrites existing translations
```
Also Chinese was updated.
Easier way to manage translations.
None.
=> Locale scripts

public/_locales/cs/messages.json, public/_locales/hu/messages.json
Completes translations:
- Hungarian (thanks to @ovari)
- Czech (thanks to @martinsustek)
Closes #353
=> Complete hu and cs translations

package.json, public/_locales/pl/messages.json, yarn.lock
This change upgrades all dependencies to their latest version. Also the languages got synced from Localazy.
More stable and secure application.
None
=> Dependency upgrades and language update

.github/workflows/nightly.yml, package-lock.json, package.json
=> Package upgrades

src/Popup.vue, src/charts/LineChart.vue, src/parts/ProjectMeta.vue, src/popup.js
This change is just a technical switch from options API to composition API for the popup component as well as related components.
Better organized code.
None
=> Composition API for Popup

src/Options.vue, src/options.js, src/parts/ProjectMeta.vue
This change is just a technical switch from options API to composition API for the options component as well as related components.
Better organized code.
None
=> Composition API for Options component

src/Options.vue, src/Popup.vue, src/Stats.vue, src/charts/BarChart.vue, src/charts/DoughnutChart.vue, src/charts/LineChart.vue, src/charts/MatrixChart.vue, src/definitions.js, src/parts/LiveAge.vue, src/stats.js, src/utils.js, vite.config.js
This change is just a technical switch from options API to composition API for the stats page component as well as related components.
Better organized code.
None
=> Composition API for stats page

.github/workflows/nightly.yml, package-lock.json, package.json, vite.config.js
Use Node 20, `actions/upload-artifact@v4` and update all dependencies.
Fix security issues.
None
=> Update workflows and dependencies

package-lock.json, package.json, src/Stats.vue
This PR contains the exclusion of virtual folders from account processing. Also, the debug output now contains the actual numbers of messages a folder contains (no accumulated async numbers anymore).
This fixes number inconsistencies when using Thunderbird's search folders or other virtual folders.
Fixes #413
=> Fix Counts
