src/Popup.vue
src/Stats.vue

* None
There is no reason for local accounts to be excluded. Deleted the filtering of account list for non local accounts.
Local accounts will be shown in the accounts list and therefor also get the stats
Closing #13

🔨 include local accounts in account list and stats

---

src/Stats.vue

Added a multicolumn layout depending on viewport width breaking points:
width > 2500px: 5 column layout
2000px < width <= 2500px: 4 column layout
1500px < width <= 2000px: 3 column layout
720px < width <= 1500px: 2 column layout
width <= 720px: 1 column layout
Available space on (ultra-)wide screens is not wasted but used to show all charts at first glance.
Closes #9

Visual improvements of chart layout

---

src/Stats.vue

Adds two-row layout of featured numbers for viewports smaller than 960px. Also prevents add-on heading from beaking on small viewports.
No more overlapping labels or horizontal overflow of featured numbers area.
Closes #10

💚 one or two row layout for numbers based on viewport

---

src/Stats.vue

solution based on this  [chartjs issue](https://github.com/chartjs/Chart.js/issues/5744)
solves #61 
2500px in calc formula is max-width of #stats
2rem is column-gap of .chart-area

🔨 min-width for chart resize issues

---

src/Stats.vue

Harden the condition for taking a date from an email header as oldest date
Exclude malformed email headers where the date property is null.
#91

🔨 exclude zero dates for date range calculation

---

public/_locales/en/messages.json
public/manifest.json
public/options.html
src/Options.vue
src/Stats.vue
src/assets/global.styl
src/options.js
vue.config.js

This PR implements add-on specific options (within a 5MB threshold):
- Dark mode flag to keep the preferred theme mode
- Local identities for recognition of sent mails in local accounts
The options above and the ability for future options
#86

➕ Add-on options

---

src/Stats.vue

Add ThirdStats logo to heading of stats page
Permanent logo on stats page
Closes #118

➕ add logo to stats page

---

public/_locales/en/messages.json
src/Popup.vue

Use a more meaningful dashboard icon in the popup, move the spinner to the accounts label (semantically more correct)
More clean and more intuitive UX
And an additional tooltip on mouseover to explain the action
Closes #129

💚 use more meaningful dashboard icon

---

public/_locales/en/messages.json
src/Options.vue
src/Popup.vue
src/Stats.vue
src/assets/global.styl
src/utils.js

This implements a caching system to only process accounts once. Accounts can be manually reprocessed. Caching system can be activated/deactivate in add-on options. Cache can be cleared in add-on options.
After initial loading, switching accounts is a lot faster.
Manual refresh button:
Options are now organized in sections. Caching is added:
Closes #130 and #131

➕ implement stats cache, revamp options

---

src/stats.js

Closes #41 
Adds the polish plualization form. Messages should be now (according to the issue description): `{0} komentarzy | {0} komentarz | {0} komentarze`
Translators should now be able to translate Third Stats to polish in full.
See #41

🔨 fix polish pluralisation rules

---

src/Options.vue

Proved a proper handler for already existing options which don't have `accounts` array property.
Make accounts option work again for affected users.
#165

🔨 fix option accounts initialization

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl
src/utils.js

Additional filter for single folder of active account on stats page. Resetable with a corresponding clear button.
More fine-grained stats about single folders. Note, that folders will not be recursively processed. Only the messages in the specified folder are processed, not in subfolders.
#44

Folder stats

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl

Additional filter *time period*, adding 2 input fields for start and end date, an apply button and a reset button.
Since the date picker of TB is buggy (especially on the default dark theme), I decided to implement the input fields as normal text fields with autoformatting (completing century, inserting dashes). Time period also works in combination with the folder filter.
Date input must be of format YYYY-MM-DD (input of YYMMDD gets autocorrected). Date input can only be between 1970-01-01 and the current day (gets autocorrected). Start date must be before end date.
Ability to get all stats for a specific time period only.
#161

Time period stats

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/charts/BarChart.vue
src/charts/LineChart.vue

Implements an option to show or hide the vertical axis for line and bar charts. It's deactivated by default, to maintain a cleaner UI.
Those who need the vertical axis values (e.g. for screenshots), can now easily activate it in the add-on options:
#170

Add ordinate option

---

public/_locales/en/messages.json
src/Popup.vue

Removes the number of messages per account from the popup page.
This heavily increases loading time of the popup.
#174

❌ remove messages count from popup

---

.gitignore
public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl

Account processing and loading got completely revamped. An option to show sum of all account stats was added:
This allows to see overall stats. Due to performance reasons, this only works if cache is enabled. Folder filter is deactivated, date range filter can be used with All Accounts (Sum).
#92

Sum account stats

---

src/Popup.vue
src/Stats.vue

Account tiles are now two column and overflow content can be reached via scrolling.
⚠ The URL of the stats page changed. Already opened stats pages have to be closed and reopened again via the popup menu.
This change allows to access an unlimited number of accounts via the popup menu.
#191

Revamp popup layout

---

src/Stats.vue

Days of January before week 1 got counted for week 53 at current years end instead of week 53 of previous year. This affected both the weeks line chart as well as the activity heatmaps. To apply this fix, data of all accounts has to be reprocessed.
#197

🔨 fix data of week 53 for weeks and days charts

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/assets/global.styl

Implements an option to handle self messages (messages from me to myself).
This can be disabled (default) to treat every email the same. It can be set to `Same Account Only` (Messages where sender and receiver are identities from the same account will be excluded) and `From Any Account` (Messages where sender and receiver are identities from any account will be excluded).
Note that only "pure self messages" are taken into account, where all recipients match the corresponding identities. If e.g. a message was sent to one of my identities and another recipient, it's not counted
#169

Self Messages

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/assets/global.styl

Adds option to define the number of entries in leaderboards. Allowed are numbers between 1 and 999 due to reasonable cache size.
No hardcoded number of contacts anymore.
Closes #183

Leader count option

---

src/Stats.vue

If URL parameter which holds the account ID is invalid (e.g. not given at all or all accounts processing was requested without Cache being enabled), the first account of the available accounts list is displayed on the stats page.
Fixes #208 B)

🔨 extend parameter handling for invalid cases

---

src/Popup.vue
src/Stats.vue

Account lists in the popup menu and on the stats page were initially listing all accounts, instead of the default setting of listing all non local accounts. This lead to unexpected behaviour for users with only one local and one non-local account.
#208

🔨 fix initial account lists

---

src/Popup.vue

A users has unwanted 1 column layout in the popup menu. This PR switches the Flex to the grid layout to always show two column account tiles.
No unwanted wrapping.
None yet.

💚 switch from flex to grid for popup account tiles

---

src/assets/global.styl

Switches and Checkboxes were 1px too tall on options page
Fix this by applying including border size.
None.

🔨 fix switch and checkbox elements size on options page

---

src/Stats.vue

When option *Self Messages* was set to "From Any Account", local identities were not being taken into account if a local account was active.
This PR includes configured local identities for this option.
None.

🔨 add local identities to global identities list

---

src/Popup.vue
src/Stats.vue

This change hardens the handling of the case, when a user only has one activated account. The "Open all stats" in the popup menu now points to this single account in that case. Also a reload of the stats page with `s=sum` shows that account properly instead of an empty account select field.

Properly handle one account list

---

src/Stats.vue
src/assets/global.styl

Adds two buttons for going to next or previous year of the activity overview.
Additional navigational elements for faster interaction.
Closes #220

➕ add years navigation

---

public/_locales/de/messages.json
public/_locales/en/messages.json
src/Stats.vue

Most "join & help improve the statements, especially those linking to GitHub, use that "Fork me on GitHub" banner.
I aimed for a bit more fun here, at least for DE & EN locales, by targeting a latent ambiguity, with a wink one might say. 😄
Additionally, being a UI aesthetics junky, I removed the "v" in front of ThirdStats's version line at the stats page's bottom - looks cleaner now. Target accomplished. 😎 If the owner approves my PR, that is. 😅
No vaccine against COVID-19, I guess. 😞
But a bit more joy, hence - maybe, in a galaxy far, far away - world peace? 🤔
None, was entirely done out of joy about my discovery that GitHub, in 2021, *_finally_* supports dark-mode! 😍🥳🤘🏻

 Aim for a bit more nerdyness & a tiny bit cleanness 😉

---

public/_locales/en/messages.json
src/Popup.vue
src/Stats.vue
src/assets/global.styl
src/charts/LineChart.vue

This change adds the overall messages count to the popup menu account tiles again. It also adds a background chart showing the annual progression of all messages (sum of sent and received messages). The data only shows up, if cache is enabled and cached date already exists for the corresponding account.
To prevent an overload of content in the account tiles and save clearness, no more metrics were added.
Quick overview of accounts messages count in the popup menu again after #178.
#175

Popup stats

---

src/Stats.vue

Tab titles with account name for single accounts on the stats page were missing.
More speaking Tab titles again.
None

🔨 set account name in tab title of stats page again

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl
src/charts/BarChart.vue

- Create groups of similar charts
- Use tab navigation for every group, even if there is only one tab (because tabs serve as heading and their tooltip as description here)
- Active tab border color indicates which email class is displayed in the corresponding chart (received, sent or both)
- Increase the size of the last chart areas when viewport is ultrawide
Stats page is now more structured and a much less messy:
Closes #230

Improve stats page layout

---

src/Stats.vue

Responsiveness is improved especially for large email addresses in the leader board section.
- Heatmaps keep their size from 1750px and wider viewports and sibling chart areas (like leader boards) adjust to the available space
- one column layout up to 1750px
#232

Adjust responsiveness

---

public/_locales/de/messages.json
public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/assets/global.styl
src/charts/BarChart.vue
src/charts/LineChart.vue
src/definitions.js
src/utils.js

This implements a comparison mode showing the total number of emails for each account. This mode was created for the years, quarters, months, weeks, daytime, weekday and month charts. To keep things simple and clean, I refrained from making a distinction between received and sent mails for each account in comparison mode - charts are always showing the total number of emails for the corresponding account.
In addition, the accounts option on the options page was extended to set a custom color for each account.
Possibility to directly compare accounts. The date range filter works in comparison mode too.
#152

Stats comparison

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/assets/global.styl
src/charts/BarChart.vue
src/charts/LineChart.vue

Option changes are now being watched on the stats page and automatically updated, Changes of *Dark mode*, *Vertical axis*, *Start of Week* and the account colors are directly applied. All other options need a window or cache refresh. Options now have a hint symbol with a tooltip that indicates, wether the stats page or the cache has do be reloaded after changing the options value.
Being forced to refresh the stats page less often.
#236

Watch option changes

---

src/Stats.vue
src/utils.js

The case of email addresses when processing accounts wasn't handled properly. Now all email addresses and identities are converted to lowercase before processing them.
More accurate numbers for sent and received, removing the need to set the same identity in different cases.
#239

🔨 unify identities to lowercase

---

README.md
public/_locales/en/messages.json
public/manifest.json
src/Stats.vue
src/utils.js

Provides the possibility to export the currently displayed data in JSON format. The export button is next to the options button in the top right corner of the stats page. It's always an export of the currently displayed data, making it possible to adjust the export by using the filter fields (accounts, folders and date range).
This requires an additional permission `downloads`.
This gives users the opportunity to evaluate the data in other programs.
#233

Data export in JSON format

---

src/Stats.vue
src/utils.js

Fixes the computed weeks chart data by taken into account, that the first days of year can belong to the last week of the previous year as well as the last days of a year can belong to the first week of the next year.
Weeks chart will show up again for date ranges that contain a day belonging to a week in another year.
Closes #267

🔨 fix weeks chart daata

---

README.md
SECURITY.md
public/manifest.json
src/Options.vue

Removes the `tabs` permission and updates permissions docs
One permission less, more transparency about permissions
#268

Revamp permissions

---

README.md

Wordsmith section to improve clarity and provide additional information
related to the projects privacy position and with respect to the extensions
permission use.
References: #271

Improve Privacy and Security section

---

src/Stats.vue

The order of received and sent folder stats got mistakenly reversed in the latest refactoring change.
Order of received first and sent second is restored.
None.

🔨 fix folder stats order

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl

This makes the account comparison switch always visible. It's inactive if...
... only one account is active in add-on options
... a single account was selected in stats account filter
In both cases it shows a corresponding tooltip making clear, why this button is inactive.
In active state, the tooltip shows what happens if the button is clicked.
Better UX because the user is way better informed about this feature.
Closes #276

Account comparison awareness

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/assets/global.styl

- Makes 'All Accounts' filter option more aware by always showing it (it's disabled for only one single activated account) and placing a corresponding hint in the accounts option on the options page.
- Also improves visibility of action buttons on the stats page (reload, export, options, year navigation) by increasing contrast between icon color and background
Improved accessibility and UX.
'All Accounts' option:
Options page:
Action buttons:
Closes #275

All accounts awareness and icon button accessibility

---

public/_locales/en/messages.json

Renames 'Self Messages' to 'Messages to Self' as discussed in #258 
More clear wording
Closes #287

Rename 'Self Messages' to 'Messages to Self'

---

public/_locales/ca/messages.json
public/_locales/cs/messages.json
public/_locales/de/messages.json
public/_locales/en/messages.json
public/_locales/es/messages.json
public/_locales/fr/messages.json
public/_locales/gl/messages.json
public/_locales/hi/messages.json
public/_locales/hu/messages.json
public/_locales/it/messages.json
public/_locales/ja/messages.json
public/_locales/pl/messages.json
public/_locales/pt/messages.json
public/_locales/ru/messages.json
public/_locales/sv/messages.json
public/_locales/th/messages.json
public/_locales/tr/messages.json
public/_locales/zh-cn/messages.json
public/_locales/zh-tw/messages.json
src/Popup.vue
src/Stats.vue

Popup language keys were improved by including amount numbers.
This reduces the use of the same translation in different contexts and provides the possibility to place the number as it suits the corresponding translation.
#295

Include numbers in popup translations

---

src/Stats.vue
src/utils.js

This expands the extraction of email addresses from strings that contain an email address without surrounding angle brackets. Example: email addresses in `John Doe <john@doe.com>` and `John Doe john@doe.com` are both recognized now.
Also email address comparison to recognize sent mails is now entirely done on lowercase strings.
Sent emails are now properly recognized as sent, even if they don't contain angle brackets are have uppercase characters.
Closes #317

Fix identity comparison

---

public/_locales/en/messages.json
src/Options.vue
src/Stats.vue
src/charts/BarChart.vue

This change creates an additional chart section for charts about tags. It adds an horizontal chart bar showing the number of emails the corresponding tag is used with. It also adds an option to show the tag bars in their corresponding color, that has been configured in Thunderbird. This is deactivated per default.
Tag stats for users utilizing tags to organize their emails:
Option to activate tag colors:
Tag stats in their corresponding colors:
Closes #328

Tags analysis

---

src/charts/BarChart.vue

This changes the tooltip interaction mode for bar charts. A tooltip is now always shown on a bar, if the cursor intersects with it.
No weird positioning glitches especially on horizontal bar chart tooltips anymore.
Closes #327

🔨 show tooltip when mouse intersects with bar

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl

This implements an icon and a notices, if a chart has no data at all.
No empty charts display anymore and user gets informed, that there is no particular chart data - therefore improved UX.
Closes #334

No data chart notices

---

public/_locales/en/messages.json
src/Stats.vue
src/assets/global.styl

This change merges two sections about email counts in the featured numbers bar into one section with a small tab/arrow navigation. It also features an additional unit _mails per quarter_.
One place for the same metric with just different units, freeing up space for a different metric.
Closes #336

Merge similar metrics for email counts

---

public/_locales/en/messages.json
src/Stats.vue

A numbers section about the count of starred and tagged mails is added in this change.
General quantitative information about how many emails are starred or tagged. Filling the empty space left by #336 again.
#328
https://github.com/devmount/third-stats/discussions/323#discussioncomment-966387

Numbers section for starred and tagged mails

---

public/_locales/en/messages.json
src/Stats.vue

This small change makes the stats page title appear just like the options page in format: ThirdStats logo + h1 general page title.
Same look and feel for headings on different ThirdStats pages.
None

Unify page titles

---

package.json
src/Stats.vue
src/stats.js
vue.config.js
yarn.lock

This upgrades Vue CLI to ^5.0.0 to apply security patches for known vulnerabilities. It also improves version retrieval and reduces target browsers to Firefox ESR only.
Security patch.
none

Upgrade Cue CLI

---

src/assets/global.styl
yarn.lock

This change adapts some dark theme colors to the dark color scheme of Thunderbird 91.
No ugly color differences in TB 91 anymore:
This may produce color issues on TB versions <91, but ThirdStats always supports the current ESR.
None.

Adapt colors

---

src/Stats.vue
src/charts/BarChart.vue
src/charts/DoughnutChart.vue
src/charts/LineChart.vue

This change implements a unified format for all charts:
Title label
3,079 dataset 1 label
1,024 dataset 2 label
Single data points are properly displayed now, numbers in tooltips are formatted, improved UX.
Closes #350 
Closes #349

Chart tooltips in a unified format

---

public/_locales/en/messages.json
src/Options.vue
src/Popup.vue
src/Stats.vue

An additional option *Live Count Up* is introduced to show live progress of calculated numbers when processing stats data. This is enabled by default.
Another visual indicator for users to see that stats data is being processed. Users on slower systems can disable this option to speed up stats processing.
Implements #248

Live Count Up

---

public/_locales/en/messages.json
public/manifest.json
src/Options.vue
src/Stats.vue
src/assets/global.styl

This change introduces automatic processing of stats data in a defined time interval. A corresponding add-on option provides the possibility to disable/enable automatic processing and set a number of minutes for the time interval. The default value is enabled with 30 minutes. If this option is changed, the stats tab needs to be reloaded.
Automatic processing only happens when the stats page is open. Reprocessing is always done for all active accounts. The current view (selected account option or filter) is kept during and after reprocessing. Live-Update of featured numbers is disabled for automatic processing. The time the data was updated is shown in the upper left as usual - with automatic processing enabled, the data shouldn't be older than the defined time interval anymore.
The strict …

Automatic Processing

---

public/_locales/en/messages.json
src/Options.vue
src/Popup.vue
src/Stats.vue
src/assets/global.styl
src/parts/ProjectMeta.vue
vue.config.js

This change introduces 5 CTA buttons at the bottom of the popup
and in the footer section of the stats and options pages
It's now much easier for user to support the project in a way that suits them.
None

Meta Information

---

public/js/background.js
src/Stats.vue

The stats page can now be opened simply by calling `stats.html` without the `s` parameter. It was a stupid mistake by me assigning a new variable to a constant 🤷🏻 
Default for opening the stats page is working now. Used for the spaces toolbar.
None.

Open stats page without parameter

---

src/assets/global.styl
src/parts/ProjectMeta.vue

Just a quick fix for secondary buttons on light mode.
Button labels become readable again
None

Fix button colors on light mode

---

public/icon-dark.svg
public/icon-light.svg
public/js/background.js

The ThirdStats icon in the spaces toolbar now matches the current theme mode.
The icon now better integrates into the spaces toolbar:
#382

Add-on icon depending on theme

---

package-lock.json
package.json
public/js/background.js
public/manifest.json
src/Popup.vue
src/Stats.vue
src/assets/global.styl
src/utils.js

This PR brings all dependencies to their latest version and migrates to Manifest v3. Also some colors where adapted to TB's redesigned color scheme. Also a bug was fixed, where the spaces icon appeared twice.
BREAKING: Strict TB min version was elevated from 91.0 to 128.0
More secure and future ready.
Fixes #441

Manifest v3

---

src/assets/global.styl

This change restores select inputs native appearance, since height and arrow indicators were broken somehow.
UI improvement.
None

Fix form select appearance

---

README.md
src/parts/ProjectMeta.vue

Since Twitter is a thing of the past, this change replaces Twitter links by a Mastodon forwarder. I could have implemented a Mastodon server selector but, well... I went the easy way there, don't blame me.

Replace Twitter by Mastodon share link

---

src/charts/BarChart.vue

This change removes the auto skip padding for axis labels completely. This way, there is still no overlapping of entries, but more labels will be shown for horizontal bar charts. With the current height of bar charts there can be 24 entries without skip:
Hopefully better UX.
Closes #433

Set autoSkipPadding for bar charts to zero

---

.github/workflows/nightly.yml
.github/workflows/validate.yml
package-lock.json
package.json
src/utils.js

This change adds a linter and provides `npm run lint` as well as a linter validation for PRs.
Ensure cleaner code.
None

Add linter: Oxlint
